package com.cug.greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.cug.greendao.PeopleInfo;
import com.cug.greendao.RegionInfo;
import com.cug.greendao.SheetInfo;
import com.cug.greendao.RecordInfo;
import com.cug.greendao.PeriodInfo;
import com.cug.greendao.HistoryRoute;
import com.cug.greendao.Notices;

import com.cug.greendao.PeopleInfoDao;
import com.cug.greendao.RegionInfoDao;
import com.cug.greendao.SheetInfoDao;
import com.cug.greendao.RecordInfoDao;
import com.cug.greendao.PeriodInfoDao;
import com.cug.greendao.HistoryRouteDao;
import com.cug.greendao.NoticesDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig peopleInfoDaoConfig;
    private final DaoConfig regionInfoDaoConfig;
    private final DaoConfig sheetInfoDaoConfig;
    private final DaoConfig recordInfoDaoConfig;
    private final DaoConfig periodInfoDaoConfig;
    private final DaoConfig historyRouteDaoConfig;
    private final DaoConfig noticesDaoConfig;

    private final PeopleInfoDao peopleInfoDao;
    private final RegionInfoDao regionInfoDao;
    private final SheetInfoDao sheetInfoDao;
    private final RecordInfoDao recordInfoDao;
    private final PeriodInfoDao periodInfoDao;
    private final HistoryRouteDao historyRouteDao;
    private final NoticesDao noticesDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        peopleInfoDaoConfig = daoConfigMap.get(PeopleInfoDao.class).clone();
        peopleInfoDaoConfig.initIdentityScope(type);

        regionInfoDaoConfig = daoConfigMap.get(RegionInfoDao.class).clone();
        regionInfoDaoConfig.initIdentityScope(type);

        sheetInfoDaoConfig = daoConfigMap.get(SheetInfoDao.class).clone();
        sheetInfoDaoConfig.initIdentityScope(type);

        recordInfoDaoConfig = daoConfigMap.get(RecordInfoDao.class).clone();
        recordInfoDaoConfig.initIdentityScope(type);

        periodInfoDaoConfig = daoConfigMap.get(PeriodInfoDao.class).clone();
        periodInfoDaoConfig.initIdentityScope(type);

        historyRouteDaoConfig = daoConfigMap.get(HistoryRouteDao.class).clone();
        historyRouteDaoConfig.initIdentityScope(type);

        noticesDaoConfig = daoConfigMap.get(NoticesDao.class).clone();
        noticesDaoConfig.initIdentityScope(type);

        peopleInfoDao = new PeopleInfoDao(peopleInfoDaoConfig, this);
        regionInfoDao = new RegionInfoDao(regionInfoDaoConfig, this);
        sheetInfoDao = new SheetInfoDao(sheetInfoDaoConfig, this);
        recordInfoDao = new RecordInfoDao(recordInfoDaoConfig, this);
        periodInfoDao = new PeriodInfoDao(periodInfoDaoConfig, this);
        historyRouteDao = new HistoryRouteDao(historyRouteDaoConfig, this);
        noticesDao = new NoticesDao(noticesDaoConfig, this);

        registerDao(PeopleInfo.class, peopleInfoDao);
        registerDao(RegionInfo.class, regionInfoDao);
        registerDao(SheetInfo.class, sheetInfoDao);
        registerDao(RecordInfo.class, recordInfoDao);
        registerDao(PeriodInfo.class, periodInfoDao);
        registerDao(HistoryRoute.class, historyRouteDao);
        registerDao(Notices.class, noticesDao);
    }
    
    public void clear() {
        peopleInfoDaoConfig.getIdentityScope().clear();
        regionInfoDaoConfig.getIdentityScope().clear();
        sheetInfoDaoConfig.getIdentityScope().clear();
        recordInfoDaoConfig.getIdentityScope().clear();
        periodInfoDaoConfig.getIdentityScope().clear();
        historyRouteDaoConfig.getIdentityScope().clear();
        noticesDaoConfig.getIdentityScope().clear();
    }

    public PeopleInfoDao getPeopleInfoDao() {
        return peopleInfoDao;
    }

    public RegionInfoDao getRegionInfoDao() {
        return regionInfoDao;
    }

    public SheetInfoDao getSheetInfoDao() {
        return sheetInfoDao;
    }

    public RecordInfoDao getRecordInfoDao() {
        return recordInfoDao;
    }

    public PeriodInfoDao getPeriodInfoDao() {
        return periodInfoDao;
    }

    public HistoryRouteDao getHistoryRouteDao() {
        return historyRouteDao;
    }

    public NoticesDao getNoticesDao() {
        return noticesDao;
    }

}
