package com.cug.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "HISTORY_ROUTE".
 */
public class HistoryRoute {

    private Long id;
    private Integer sheetId;
    private Integer periodId;
    private String points;
    private String startTime;
    private String endTime;
    private Integer generId;

    public HistoryRoute() {
    }

    public HistoryRoute(Long id) {
        this.id = id;
    }

    public HistoryRoute(Long id, Integer sheetId, Integer periodId, String points, String startTime, String endTime, Integer generId) {
        this.id = id;
        this.sheetId = sheetId;
        this.periodId = periodId;
        this.points = points;
        this.startTime = startTime;
        this.endTime = endTime;
        this.generId = generId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getSheetId() {
        return sheetId;
    }

    public void setSheetId(Integer sheetId) {
        this.sheetId = sheetId;
    }

    public Integer getPeriodId() {
        return periodId;
    }

    public void setPeriodId(Integer periodId) {
        this.periodId = periodId;
    }

    public String getPoints() {
        return points;
    }

    public void setPoints(String points) {
        this.points = points;
    }

    public String getStartTime() {
        return startTime;
    }

    public void setStartTime(String startTime) {
        this.startTime = startTime;
    }

    public String getEndTime() {
        return endTime;
    }

    public void setEndTime(String endTime) {
        this.endTime = endTime;
    }

    public Integer getGenerId() {
        return generId;
    }

    public void setGenerId(Integer generId) {
        this.generId = generId;
    }

}
