package com.cug.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import java.io.Serializable;

/**
 * Entity mapped to table "PEOPLE_INFO".
 */
public class PeopleInfo implements Serializable {
    private static final long serialVersionUID = -758459502806858414L;
    private Long id;
    private String peopleName;
    private String name;
    private Integer teamId;
    private String peoplePassword;
    private Integer branchId;
    private String branchName;
    private String branchType;
    private String company;
    private String teamName;
    private boolean isLogin;

    public PeopleInfo() {
    }

    public PeopleInfo(Long id) {
        this.id = id;
    }

    public PeopleInfo(Long id, String peopleName, String name, Integer teamId, String peoplePassword, Integer branchId, String branchName, String branchType, String company, String teamName, boolean isLogin) {
        this.id = id;
        this.peopleName = peopleName;
        this.name = name;
        this.teamId = teamId;
        this.peoplePassword = peoplePassword;
        this.branchId = branchId;
        this.branchName = branchName;
        this.branchType = branchType;
        this.company = company;
        this.teamName = teamName;
        this.isLogin = isLogin;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getPeopleName() {
        return peopleName;
    }

    public void setPeopleName(String peopleName) {
        this.peopleName = peopleName;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getTeamId() {
        return teamId;
    }

    public void setTeamId(Integer teamId) {
        this.teamId = teamId;
    }

    public String getPeoplePassword() {
        return peoplePassword;
    }

    public void setPeoplePassword(String peoplePassword) {
        this.peoplePassword = peoplePassword;
    }

    public Integer getBranchId() {
        return branchId;
    }

    public void setBranchId(Integer branchId) {
        this.branchId = branchId;
    }

    public String getBranchName() {
        return branchName;
    }

    public void setBranchName(String branchName) {
        this.branchName = branchName;
    }

    public String getBranchType() {
        return branchType;
    }

    public void setBranchType(String branchType) {
        this.branchType = branchType;
    }

    public String getCompany() {
        return company;
    }

    public void setCompany(String company) {
        this.company = company;
    }

    public String getTeamName() {
        return teamName;
    }

    public void setTeamName(String teamName) {
        this.teamName = teamName;
    }

    public boolean getIsLogin() {
        return isLogin;
    }

    public void setIsLogin(boolean isLogin) {
        this.isLogin = isLogin;
    }

}
