package com.cug.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "PERIOD_INFO".
 */
public class PeriodInfo {

    private Long id;
    private Integer periodId;
    private Integer sheetId;
    private String periodShift;
    private String periodTime;

    public PeriodInfo() {
    }

    public PeriodInfo(Long id) {
        this.id = id;
    }

    public PeriodInfo(Long id, Integer periodId, Integer sheetId, String periodShift, String periodTime) {
        this.id = id;
        this.periodId = periodId;
        this.sheetId = sheetId;
        this.periodShift = periodShift;
        this.periodTime = periodTime;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getPeriodId() {
        return periodId;
    }

    public void setPeriodId(Integer periodId) {
        this.periodId = periodId;
    }

    public Integer getSheetId() {
        return sheetId;
    }

    public void setSheetId(Integer sheetId) {
        this.sheetId = sheetId;
    }

    public String getPeriodShift() {
        return periodShift;
    }

    public void setPeriodShift(String periodShift) {
        this.periodShift = periodShift;
    }

    public String getPeriodTime() {
        return periodTime;
    }

    public void setPeriodTime(String periodTime) {
        this.periodTime = periodTime;
    }

}
