package com.cug.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.cug.greendao.PeriodInfo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "PERIOD_INFO".
*/
public class PeriodInfoDao extends AbstractDao<PeriodInfo, Long> {

    public static final String TABLENAME = "PERIOD_INFO";

    /**
     * Properties of entity PeriodInfo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property PeriodId = new Property(1, Integer.class, "periodId", false, "PERIOD_ID");
        public final static Property SheetId = new Property(2, Integer.class, "sheetId", false, "SHEET_ID");
        public final static Property PeriodShift = new Property(3, String.class, "periodShift", false, "PERIOD_SHIFT");
        public final static Property PeriodTime = new Property(4, String.class, "periodTime", false, "PERIOD_TIME");
    };


    public PeriodInfoDao(DaoConfig config) {
        super(config);
    }
    
    public PeriodInfoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"PERIOD_INFO\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"PERIOD_ID\" INTEGER," + // 1: periodId
                "\"SHEET_ID\" INTEGER," + // 2: sheetId
                "\"PERIOD_SHIFT\" TEXT," + // 3: periodShift
                "\"PERIOD_TIME\" TEXT);"); // 4: periodTime
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"PERIOD_INFO\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, PeriodInfo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Integer periodId = entity.getPeriodId();
        if (periodId != null) {
            stmt.bindLong(2, periodId);
        }
 
        Integer sheetId = entity.getSheetId();
        if (sheetId != null) {
            stmt.bindLong(3, sheetId);
        }
 
        String periodShift = entity.getPeriodShift();
        if (periodShift != null) {
            stmt.bindString(4, periodShift);
        }
 
        String periodTime = entity.getPeriodTime();
        if (periodTime != null) {
            stmt.bindString(5, periodTime);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public PeriodInfo readEntity(Cursor cursor, int offset) {
        PeriodInfo entity = new PeriodInfo( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1), // periodId
            cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2), // sheetId
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // periodShift
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4) // periodTime
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, PeriodInfo entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setPeriodId(cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1));
        entity.setSheetId(cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2));
        entity.setPeriodShift(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setPeriodTime(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(PeriodInfo entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(PeriodInfo entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
