package com.cug.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "RECORD_INFO".
 */
public class RecordInfo {

    private Long id;
    private Integer recordId;
    private String recordGps;
    private String recordAsws;
    private Integer recordError;
    private String recordPic;
    private String recordStart;
    private String recordEnd;
    private String recordSub;
    private Boolean recordStatus;
    private Integer checkerId;
    private String recordNote;
    private String checkTime;
    private boolean isChanged;
    private String responseId;

    public RecordInfo() {
    }

    public RecordInfo(Long id) {
        this.id = id;
    }

    public RecordInfo(Long id, Integer recordId, String recordGps, String recordAsws, Integer recordError, String recordPic, String recordStart, String recordEnd, String recordSub, Boolean recordStatus, Integer checkerId, String recordNote, String checkTime, boolean isChanged, String responseId) {
        this.id = id;
        this.recordId = recordId;
        this.recordGps = recordGps;
        this.recordAsws = recordAsws;
        this.recordError = recordError;
        this.recordPic = recordPic;
        this.recordStart = recordStart;
        this.recordEnd = recordEnd;
        this.recordSub = recordSub;
        this.recordStatus = recordStatus;
        this.checkerId = checkerId;
        this.recordNote = recordNote;
        this.checkTime = checkTime;
        this.isChanged = isChanged;
        this.responseId = responseId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getRecordId() {
        return recordId;
    }

    public void setRecordId(Integer recordId) {
        this.recordId = recordId;
    }

    public String getRecordGps() {
        return recordGps;
    }

    public void setRecordGps(String recordGps) {
        this.recordGps = recordGps;
    }

    public String getRecordAsws() {
        return recordAsws;
    }

    public void setRecordAsws(String recordAsws) {
        this.recordAsws = recordAsws;
    }

    public Integer getRecordError() {
        return recordError;
    }

    public void setRecordError(Integer recordError) {
        this.recordError = recordError;
    }

    public String getRecordPic() {
        return recordPic;
    }

    public void setRecordPic(String recordPic) {
        this.recordPic = recordPic;
    }

    public String getRecordStart() {
        return recordStart;
    }

    public void setRecordStart(String recordStart) {
        this.recordStart = recordStart;
    }

    public String getRecordEnd() {
        return recordEnd;
    }

    public void setRecordEnd(String recordEnd) {
        this.recordEnd = recordEnd;
    }

    public String getRecordSub() {
        return recordSub;
    }

    public void setRecordSub(String recordSub) {
        this.recordSub = recordSub;
    }

    public Boolean getRecordStatus() {
        return recordStatus;
    }

    public void setRecordStatus(Boolean recordStatus) {
        this.recordStatus = recordStatus;
    }

    public Integer getCheckerId() {
        return checkerId;
    }

    public void setCheckerId(Integer checkerId) {
        this.checkerId = checkerId;
    }

    public String getRecordNote() {
        return recordNote;
    }

    public void setRecordNote(String recordNote) {
        this.recordNote = recordNote;
    }

    public String getCheckTime() {
        return checkTime;
    }

    public void setCheckTime(String checkTime) {
        this.checkTime = checkTime;
    }

    public boolean getIsChanged() {
        return isChanged;
    }

    public void setIsChanged(boolean isChanged) {
        this.isChanged = isChanged;
    }

    public String getResponseId() {
        return responseId;
    }

    public void setResponseId(String responseId) {
        this.responseId = responseId;
    }

}
