package com.cug.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import java.io.Serializable;

/**
 * Entity mapped to table "REGION_INFO".
 */
public class RegionInfo implements Serializable {
    private static final long serialVersionUID = -758459502806858414L;
    private Long id;
    private int regionId;
    private Integer sheetId;
    private String branch;
    private String regionName;
    private String regionIntro;
    private String regionGps;
    private String regionQrcode;
    private Integer regionSort;
    private String regionType;
    private String regionRange;
    private Integer periodId;
    private Integer ptrId;
    private Boolean isDone;

    public RegionInfo() {
    }

    public RegionInfo(Long id) {
        this.id = id;
    }

    public RegionInfo(Long id, int regionId, Integer sheetId, String branch, String regionName, String regionIntro, String regionGps, String regionQrcode, Integer regionSort, String regionType, String regionRange, Integer periodId, Integer ptrId, Boolean isDone) {
        this.id = id;
        this.regionId = regionId;
        this.sheetId = sheetId;
        this.branch = branch;
        this.regionName = regionName;
        this.regionIntro = regionIntro;
        this.regionGps = regionGps;
        this.regionQrcode = regionQrcode;
        this.regionSort = regionSort;
        this.regionType = regionType;
        this.regionRange = regionRange;
        this.periodId = periodId;
        this.ptrId = ptrId;
        this.isDone = isDone;
    }

    public RegionInfo(int regionId, Integer periodId, Integer sheetId, String regionName, String regionIntro, Integer
            regionSort, String regionType, Integer ptrId, Boolean isDone,String regionGps) {
        this.regionId = regionId;
        this.periodId = periodId;
        this.sheetId = sheetId;
        this.regionName = regionName;
        this.regionIntro = regionIntro;
        this.regionSort = regionSort;
        this.regionType = regionType;
        this.ptrId = ptrId;
        this.isDone = isDone;
        this.regionGps=regionGps;
    }
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getRegionId() {
        return regionId;
    }

    public void setRegionId(int regionId) {
        this.regionId = regionId;
    }

    public Integer getSheetId() {
        return sheetId;
    }

    public void setSheetId(Integer sheetId) {
        this.sheetId = sheetId;
    }

    public String getBranch() {
        return branch;
    }

    public void setBranch(String branch) {
        this.branch = branch;
    }

    public String getRegionName() {
        return regionName;
    }

    public void setRegionName(String regionName) {
        this.regionName = regionName;
    }

    public String getRegionIntro() {
        return regionIntro;
    }

    public void setRegionIntro(String regionIntro) {
        this.regionIntro = regionIntro;
    }

    public String getRegionGps() {
        return regionGps;
    }

    public void setRegionGps(String regionGps) {
        this.regionGps = regionGps;
    }

    public String getRegionQrcode() {
        return regionQrcode;
    }

    public void setRegionQrcode(String regionQrcode) {
        this.regionQrcode = regionQrcode;
    }

    public Integer getRegionSort() {
        return regionSort;
    }

    public void setRegionSort(Integer regionSort) {
        this.regionSort = regionSort;
    }

    public String getRegionType() {
        return regionType;
    }

    public void setRegionType(String regionType) {
        this.regionType = regionType;
    }

    public String getRegionRange() {
        return regionRange;
    }

    public void setRegionRange(String regionRange) {
        this.regionRange = regionRange;
    }

    public Integer getPeriodId() {
        return periodId;
    }

    public void setPeriodId(Integer periodId) {
        this.periodId = periodId;
    }

    public Integer getPtrId() {
        return ptrId;
    }

    public void setPtrId(Integer ptrId) {
        this.ptrId = ptrId;
    }

    public Boolean getIsDone() {
        return isDone;
    }

    public void setIsDone(Boolean isDone) {
        this.isDone = isDone;
    }

}
